
<meta name="keywords" content="{{$post->keyword}}">
<meta property="og:description" content="{{$post->meta}}"/>
<meta property="article:tag" content="{{$post->tag1}}"/>
<meta property="article:tag" content="{{$post->tag2}}"/>
<meta property="article:tag" content="{{$post->tag3}}"/>
<meta property="article:tag" content="{{$post->tag4}}"/>
<meta property="article:tag" content="{{$post->tag5}}"/>
<meta property="article:tag" content="{{$post->tag6}}"/>
<meta property="article:tag" content="{{$post->tag7}}"/>
<meta property="article:tag" content="{{$post->tag8}}"/>
<meta property="article:tag" content="{{$post->tag9}}"/>
<meta property="article:tag" content="{{$post->tag10}}"/>
<meta property="article:tag" content="{{$post->tag11}}"/>
<meta property="article:tag" content="{{$post->tag12}}"/>
<meta property="article:tag" content="{{$post->tag13}}"/>
<meta property="article:tag" content="{{$post->tag14}}"/>
<meta property="article:tag" content="{{$post->tag15}}"/>
<meta name="twitter:description" content="{{$post->meta}}"/>