version: '3.7'
services:
  nginx_production:
    build:
      context: deploy/nginx
    volumes:
      - ./:/var/www/html
      - /var/www/static/_images:/var/www/html/public/_images
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx/php.conf:/etc/nginx/php.conf
    restart: always
    links:
      - production:fpm
    environment:
      - VIRTUAL_HOST=shazdemosafer.com,koochita.com
      
  production:
    image: ${PRODUCTION_IMAGE-registry.gitlab.com/shazdemosafer/pro_shazde}
    restart: always
    volumes:
      - ./:/var/www/html
      - /var/www/static/:/var/www/assets/
      - ./deploy/fpm/php-fpm.d:/usr/local/etc/php-fpm.d
  IE:
    image: java:8-alpine
    restart: always
    volumes:
      - ./app:/app
    ports:
      - '8080:8080'
    command: ["java", "-jar", "/app/IE.jar"]

networks:
  default:
    external: true
    name: shazde
